import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService as PrismaService } from '../database/database.service';

@Injectable()
export class ReportService {
  constructor(private readonly prisma: PrismaService) {}

  async getReports(userId: string) {
    return this.prisma.report.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' }
    });
  }

  async getReport(userId: string, id: string) {
    const report = await this.prisma.report.findUnique({
      where: { id, userId }
    });
    if (!report) throw new NotFoundException('Report not found');
    return report;
  }

  async createReport(userId: string, title: string, type: string, tags?: string) {
    // Generate a mock report based on type for V1.0
    const content = this.generateMockReportContent(type);
    
    return this.prisma.report.create({
      data: {
        userId,
        title,
        type,
        content,
        tags
      }
    });
  }

  private generateMockReportContent(type: string): string {
    if (type === 'PORTFOLIO') {
      return `## Portfolio Performance Review\n\nYour portfolio has seen a **12.4%** increase over the last quarter. \n\n### Asset Allocation\n*   **Equities**: 65%\n*   **Crypto**: 15%\n*   **Cash**: 20%\n\n> **AI Insight**: Your allocation to technology equities is heavily concentrated. Consider diversifying into defensive sectors to mitigate risk in a high-interest rate environment.`;
    }
    return `## AI Market Summary\n\nThe broader market remains resilient despite inflationary pressures. \n\n### Key Highlights\n1.  **Tech Sector**: Rebounding strongly on AI optimism.\n2.  **Bonds**: Yields stabilizing around 4.2%.\n\n*Generated by TradeOXX AI*`;
  }
}
